/*
Copyright (C) 1994-1995 Apogee Software, Ltd.
Copyright (C) 2002-2015 icculus.org, GNU/Linux port
Copyright (C) 2017-2018 Steven LeVesque
Copyright (C) 2025 lunarmeadow (she/her)
Copyright (C) 2025 erysdren (it/its)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef _KPFDATA_H
#define _KPFDATA_H

#include "miniz.h"
#include "miniz_zip.h"
#include "rt_def.h"

#ifndef ARRAY_COUNT
#define ARRAY_COUNT(a) (sizeof(a)/sizeof(*a))
#endif

// generated by ZipChar
static const char *betaWalls[] = {
    "/wad/wall/WALB03.png",
    "/wad/wall/WALB04.png",
    "/wad/wall/WALB05.png",
    "/wad/wall/WALB06.png",
    "/wad/wall/WALB07.png",
    "/wad/wall/WALB08.png",
    "/wad/wall/WALB13.png",
    "/wad/wall/WALB14.png",
    "/wad/wall/WALB15.png",
    "/wad/wall/WALB16.png",
    "/wad/wall/WALB17.png",
    "/wad/wall/WALB18.png",
    "/wad/wall/WALB19.png",
    "/wad/wall/WALB20.png",
    "/wad/wall/WALB21.png",
    "/wad/wall/WALB26.png",
    "/wad/wall/WALB27.png",
    "/wad/wall/WALB28.png",
    "/wad/wall/WALB40.png",
    "/wad/wall/WALB41.png",
    "/wad/wall/WALB42.png",
    "/wad/wall/WALB44.png",
    "/wad/wall/WALB46.png",
    "/wad/wall/WALB48.png",
    "/wad/wall/WALB51.png",
    "/wad/wall/WALB58.png",
    "/wad/wall/WALB59.png",
    "/wad/wall/WALB60.png",
    "/wad/wall/WALB61.png",
    "/wad/wall/WALB69.png",
    "/wad/wall/WALB70.png",
    "/wad/wall/WALB71.png"
};

static const char *floors[] = {
    "/wad/flrcl/FLOOR1.png",
    "/wad/flrcl/FLOOR10.png",
    "/wad/flrcl/FLOOR11.png",
    "/wad/flrcl/FLOOR12.png",
    "/wad/flrcl/FLOOR14.png",
    "/wad/flrcl/FLOOR17.png",
    "/wad/flrcl/FLOOR4.png",
    "/wad/flrcl/FLOOR5.png",
    "/wad/flrcl/FLOOR6.png"
};

static const char *ceils[] = {
    "/wad/flrcl/CEIL12.png",
    "/wad/flrcl/CEIL13.png",
    "/wad/flrcl/CEIL17.png",
    "/wad/flrcl/CEIL2.png",
    "/wad/flrcl/CEIL5.png",
    "/wad/flrcl/CEIL6.png"
};

static const char *bigJohnHaha[] = {
    "/wad/shape/BIGJDEAD.png",
    "/wad/shape/BIGJDIE1.png",
    "/wad/shape/BIGJDIE2.png",
    "/wad/shape/BIGJDIE3.png",
    "/wad/shape/BIGJDIE4.png",
    "/wad/shape/BIGJPAIN1.png",
    "/wad/shape/BIGJPAIN2.png",
    "/wad/shape/BIGJS1.png",
    "/wad/shape/BIGJS2.png",
    "/wad/shape/BIGJS3.png",
    "/wad/shape/BIGJS4.png",
    "/wad/shape/BIGJS5.png",
    "/wad/shape/BIGJS6.png",
    "/wad/shape/BIGJS7.png",
    "/wad/shape/BIGJS8.png",
    "/wad/shape/BIGJSHOO1.png",
    "/wad/shape/BIGJSHOO2.png",
    "/wad/shape/BIGJSHOO3.png",
    "/wad/shape/BIGJSHOO4.png",
    "/wad/shape/BIGJTOSS1.png",
    "/wad/shape/BIGJTOSS2.png",
    "/wad/shape/BIGJTOSS3.png",
    "/wad/shape/BIGJTOSS4.png",
    "/wad/shape/BIGJTOSS5.png",
    "/wad/shape/BIGJTOSS6.png",
    "/wad/shape/BIGJTOSS7.png",
    "/wad/shape/BIGJTOSS8.png",
    "/wad/shape/BIGJW11.png",
    "/wad/shape/BIGJW12.png",
    "/wad/shape/BIGJW13.png",
    "/wad/shape/BIGJW14.png",
    "/wad/shape/BIGJW15.png",
    "/wad/shape/BIGJW16.png",
    "/wad/shape/BIGJW17.png",
    "/wad/shape/BIGJW18.png",
    "/wad/shape/BIGJW21.png",
    "/wad/shape/BIGJW22.png",
    "/wad/shape/BIGJW23.png",
    "/wad/shape/BIGJW24.png",
    "/wad/shape/BIGJW25.png",
    "/wad/shape/BIGJW26.png",
    "/wad/shape/BIGJW27.png",
    "/wad/shape/BIGJW28.png",
    "/wad/shape/BIGJW31.png",
    "/wad/shape/BIGJW32.png",
    "/wad/shape/BIGJW33.png",
    "/wad/shape/BIGJW34.png",
    "/wad/shape/BIGJW35.png",
    "/wad/shape/BIGJW36.png",
    "/wad/shape/BIGJW37.png",
    "/wad/shape/BIGJW38.png",
    "/wad/shape/BIGJW41.png",
    "/wad/shape/BIGJW42.png",
    "/wad/shape/BIGJW43.png",
    "/wad/shape/BIGJW44.png",
    "/wad/shape/BIGJW45.png",
    "/wad/shape/BIGJW46.png",
    "/wad/shape/BIGJW47.png",
    "/wad/shape/BIGJW48.png"
};

boolean FetchBetaWalls(mz_zip_archive kpfArc);

#endif