name: Barrett CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

    - name: Create build target
      run: cmake -Bcmake-build-barrett -DCMAKE_BUILD_TYPE=Release -S.
    - name: Build
      run: cmake --build cmake-build-barrett

