name: Barrett CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2 + mixer dev libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev
    - name: Create build target
      run: cmake -Bcmake-build-barrett -DCMAKE_BUILD_TYPE=Release -S.
    - name: Build
      run: cmake --build cmake-build-barrett

